export const LOADING_PHRASES = [
  'ESTABELECENDO CONEXÃO SEGURA...',
  'VERIFICANDO INTEGRIDADE DA REDE...',
  'SINCRONIZANDO CHAVES ZERO-TRUST...',
  'DESCRIPTOGRAFANDO ACESSOS...',
  'VALIDANDO CREDENCIAIS MASTER...',
  'CARREGANDO COMANDO CENTRAL...'
];